# Generated by Django 3.1.1 on 2020-10-01 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(blank=True, choices=[('NEW', 'Новая'), ('PLANNED', 'Запланированная'), ('IN_WORK', 'В работе'), ('COMPLETED', 'Завершённая')], default='NEW', max_length=100, verbose_name='Статус')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Планируемая дата завершения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ('-add_date',),
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(blank=True, choices=[('NEW', 'Новая'), ('PLANNED', 'Запланированная'), ('IN_WORK', 'В работе'), ('COMPLETED', 'Завершённая')], default='NEW', max_length=100, verbose_name='Статус')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Планируемая дата завершения')),
                ('edit_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ('-edit_time',),
            },
        ),
    ]
