# Generated by Django 3.1.1 on 2020-10-01 10:11

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, validators=[api.utils.validate_completion_date], verbose_name='Планируемая дата завершения'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, validators=[api.utils.validate_completion_date], verbose_name='Планируемая дата завершения'),
        ),
    ]
