# Generated by Django 3.1.1 on 2020-09-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200930_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Планируемая дата завершения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Планируемая дата завершения'),
        ),
    ]
