# Generated by Django 3.1.1 on 2020-10-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201001_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-add_date',)},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='add_time',
            new_name='add_date',
        ),
        migrations.RenameField(
            model_name='taskhistory',
            old_name='add_time',
            new_name='add_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Планируемая дата завершения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'Новая'), ('PLANNED', 'Запланированная'), ('IN_WORK', 'В работе'), ('COMPLETED', 'Завершённая')], default='NEW', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Планируемая дата завершения'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'Новая'), ('PLANNED', 'Запланированная'), ('IN_WORK', 'В работе'), ('COMPLETED', 'Завершённая')], default='NEW', max_length=100, verbose_name='Статус'),
        ),
    ]
